### ISSUE TITLE
Please upgrade Net7.0 for this plugin

### ISSUE THREAD

**Issue by wubinwww** [Bl4ckSh4rk/PKHeXWC3Plugin#1]
Hello, Mr. BlackShark! I am a friend of pplouf, and your PKHeXMirageIslandPlugin is my Chinese translation. I would like to ask if you can upgrade PKHeXWC3 to Net7.0 if you have time. I think this plug-in still has value to save, such as e-Card Berries function.

**Comment by Bl4ckSh4rk** [comment]
I will update it to NET7, actually I am already working on it. But I have to completely rewrite the plugin as it has some major issues in its current state and that will take a while.
It might look like I abandoned this plugin, but don't worry, that's not the case!

**Comment by wubinwww** [comment]
Thank you very much. I will keep an eye on your developments. Although I don't use github very much, I will make a Chinese translation as soon as possible after your plug-in is upgraded and upload it to you with pplouf. Our resources are synchronized.

**Comment by Bl4ckSh4rk** [comment]
I pushed an update. It's not ready for release yet, but you can already translated it.
