### ISSUE TITLE
This plugin causes time based events to no longer occur.

### ISSUE THREAD

**Issue by stefannovak** [Bl4ckSh4rk/PKHeXWC3Plugin#4]
Hi, I was wondering if it was known that using these events breaks the in game clock. Ever since using this for the Mystic Ticket, Aurora Ticket and Eon Ticket events, I can no longer do time based events like the Lilycove lottery.

**Comment by Bl4ckSh4rk** [comment]
This should not be caused by my plugin or by mystery events. Sounds more like an issue with your emulator or save dumper.

Did you only import the events or did you do other edits? What happens if you only do other edits without using this plugin?
Can you provide steps to reproduce this?

**Comment by stefannovak** [comment]
> This should not be caused by my plugin or by mystery events. Sounds more like an issue with your emulator or save dumper.
> 
> Did you only import the events or did you do other edits? What happens if you only do other edits without using this plugin? Can you provide steps to reproduce this?

Hey, good to hear! I used a Gameboy SP and a legit copy of Emerald. I need to retrace my steps a bit, looking through your code I couldn't understand how that would happen either.

I used the Epilogue Operator and this plugin to inject the Eon ticket to a sapphire cartridge with a dead battery, and then mixed records with my Emerald. I wonder if that's what caused it.

Cheers!
